#!/bin/bash
echo "### This script was invoked by the following command: "
printf '%q ' "$0" "$@"
echo "###"

# This script watches the prune sessions timer and service, and prints the logs in real time. It also starts the timer at the beginning and stops it at the end.
# Note that no virtual environment is activated in this script, so it relies on the systemd 
# service to activate the virtual environment and run the prune sessions command. 
# This is intentional, as it allows us to test the systemd service and timer without any interference from the current shell environment.

# Exit immediately if a command fails
set -e




systemctl --user start "ticketweb-authsystem-prunesessions@$BUILD_ID.timer"



journalctl --user -fu "ticketweb-authsystem-prunesessions@$BUILD_ID.service"

systemctl --user stop  "ticketweb-authsystem-prunesessions@$BUILD_ID.timer"



