[metadata]
name = ticketweb-authsystem-server-WALTONM
version = 0.0.1
author = Michael Walton
author_email = waltonm@queensu.ca
description = JWT token server for OUR SIS web project
# long_description = file: README.md
# long_description_content_type = text/markdown
# url = https://github.com/pypa/sampleproject
# project_urls =
#    Bug Tracker = https://github.com/pypa/sampleproject/issues
classifiers =
    Programming Language :: Python :: 3
    License :: OSI Approved :: MIT License
    Operating System :: OS Independent

[options]
package_dir =
    = src
packages = 
   find:

install_requires =
    cryptography >= 37.0
    falcon >= 3.1
    gunicorn >= 20.1
    PyJWT >= 2.3
    python-ldap >= 3.4
    psycopg2 >= 2.9
    json5
    pip-system-certs

scripts =
   bin/ticketweb-authsystem-mk-db-installer
   bin/ticketweb-authsystem-install
   bin/ticketweb-authsystem-server
   bin/ticketweb-authsystem-register-app
   bin/ticketweb-authsystem-prunesessions
   bin/ticketweb-authsystem-setenv
   bin/ticketweb-authsystem-gen-apache-config-fragment
   

include_package_data = True


# [options.package_data]
# ticketweb_authsystem_server = 
#    back_end/sql/*.sql
#    session_storage_schema.sql
#    ticketweb-authsystem-create-db-schema
#    systemd-unit-files/*.service
#    systemd-unit-files/*.timer
#    systemd-unit-files/ticketweb-authsystem-prunesessions.service.d/*.conf
#    config.json5
#    # frontend_module/*
#    # frontend_module/**/*
#    # The above two lines would override the directions given in MANIFEST.in, which 
#    # explicitly includes the built frontend module,
#    # while excluding the node_modules subdirectory, which is just a staging directory for the frontend module build process, 
#    # and may contain very large amount of file content that we don't want to include in the package.
#    # This is in necessary because, in development mode, upon installing, we will have built the module in-place.



[options.entry_points]
console_scripts =
    ticketweb-export-systemd = ticketweb_authsystem_server.cli:export_configs_cli
    ticketweb-export-session-schema = ticketweb_authsystem_server.cli:export_session_schema_cli


python_requires = >=3.6

[options.packages.find]
where = src
exclude =
#     frontend_module
#     frontend_module.*
#   ticketweb_authsystem_server.frontend_module
#   ticketweb_authsystem_server.frontend_module.*