

[metadata]
name = ticketweb-apps-ithelp-WALTONM
version = 0.0.1
author = Michael Walton
author_email = waltonm@queensu.ca
description = IT Help application server OUR SIS web project
# long_description = file: README.md
# long_description_content_type = text/markdown
# url = https://github.com/pypa/sampleproject
# project_urls =
#    Bug Tracker = https://github.com/pypa/sampleproject/issues
classifiers =
    Programming Language :: Python :: 3
    License :: OSI Approved :: MIT License
    Operating System :: OS Independent

[options]
package_dir =
    = src
packages = find:
python_requires = >=3.6

install_requires =
    cryptography >= 37.0
    falcon >= 3.1
    gunicorn >= 20.1
    PyJWT >= 2.3
    python-ldap >= 3.4
    requests >= 2.27
    requests-toolbelt >= 0.9.1
    json5

    ticketweb-applib-WALTONM == 0.0.1

scripts =
   bin/ticketweb-apps-ithelp-install
   bin/ticketweb-apps-ithelp-server
   bin/ticketweb-apps-ithelp-setenv
   bin/ticketweb-apps-ithelp-frontend-servebuild

include_package_data = True


[options.package_data]
ticketweb_apps_ithelp = 
    back_end/sql/*.sql
    systemd-unit-files/*.service
    app-server-config.json5
    frontend-config.json5
    shared-data/init_data.json
    # frontend_module/*
    # frontend_module/**/*
    # The above two lines would override the directions given in MANIFEST.in, which 
    # explicitly includes the built frontend module,
    # while excluding the node_modules subdirectory, which is just a staging directory for the frontend module build process, 
    # and may contain very large amount of file content that we don't want to include in the package.
    # This is in necessary because, in development mode, upon installing, we will have built the module in-place.



[options.entry_points]
console_scripts =
    ticketweb-export-systemd = ticketweb_apps_ithelp.cli:export_configs_cli



python_requires = >=3.6

[options.packages.find]
where = src
